// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiaqjmvqdckfhwvpnbqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pYXFqbXZxZGNrZmh3dnBuYnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDE2NDIsImV4cCI6MjA3MDExNzY0Mn0.APNJ--CQzDc2zAIX6lh-gxvbUmSgPFG-MCDUni6CZqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});